var dataSets = {
    "fundamental": "Fundamental data",
    "analyst": "Analyst data",
    "broker": "Broker",
    "news": "News data",
    "socialmedia": "Social media data",
    "sentiment": "Sentiment data",
    "pv": "Price volume data",
    "option": "Option data",
    "earnings": "Earnings",
    "insiders": "Insiders",
    "institutions": "Instiutional Ownership Data",
    "shortinterest": "Short interest data",
    "macro": "Macro data",
    "other": "Other",
    "risk": "Risk data",
    "model": "Model data",
};
var regions = ['USA', 'ASI', 'CHN', 'EUR', 'GLB', 'HKG', 'KOR', 'TWN', 'AMR', 'JPN'];
var url = "https://api.worldquantbrain.com/users/self/activities/diversity?grouping=region,delay,dataCategory"

var non_data = [
    {'x': 'GLB', 'y': 'Broker'},
    {'x': 'USA', 'y': 'Broker'},
    {'x': 'CHN', 'y': 'Broker'},
    {'x': 'AMR', 'y': 'Broker'},
    {'x': 'HKG', 'y': 'Broker'},
    {'x': 'TWN', 'y': 'Broker'},
    {'x': 'ASI', 'y': 'Broker'},
    {'x': 'EUR', 'y': 'Broker'},
    {'x': 'KOR', 'y': 'Broker'},
    {'x': 'TWN', 'y': 'Insiders'},
    {'x': 'GLB', 'y': 'Insiders'},
    {'x': 'CHN', 'y': 'Insiders'},
    {'x': 'GLB', 'y': 'Instiutional Ownership Data'},
    {'x': 'CHN', 'y': 'Instiutional Ownership Data'},
    {'x': 'HKG', 'y': 'Instiutional Ownership Data'},
    {'x': 'TWN', 'y': 'Instiutional Ownership Data'},
    {'x': 'ASI', 'y': 'Instiutional Ownership Data'},
    {'x': 'KOR', 'y': 'Instiutional Ownership Data'},
    {'x': 'CHN', 'y': 'Macro data'},
    {'x': 'HKG', 'y': 'Macro data'},
    {'x': 'TWN', 'y': 'Macro data'},
    {'x': 'ASI', 'y': 'Macro data'},
    {'x': 'KOR', 'y': 'Macro data'},
    {'x': 'CHN', 'y': 'Option data'},
    {'x': 'HKG', 'y': 'Option data'},
    {'x': 'TWN', 'y': 'Option data'},
    {'x': 'ASI', 'y': 'Option data'},
    {'x': 'KOR', 'y': 'Option data'},
    {'x': 'CHN', 'y': 'Risk data'},
    {'x': 'GLB', 'y': 'Sentiment data'},
    {'x': 'CHN', 'y': 'Sentiment data'},
    {'x': 'AMR', 'y': 'Sentiment data'},
    {'x': 'HKG', 'y': 'Sentiment data'},
    {'x': 'TWN', 'y': 'Sentiment data'},
    {'x': 'ASI', 'y': 'Sentiment data'},
    {'x': 'KOR', 'y': 'Sentiment data'},
    {'x': 'TWN', 'y': 'Social media data'},
    {'x': 'KOR', 'y': 'Social media data'}
]

var non_data_delay0 = [
    {'x': 'GLB', 'y': 'Fundamental data'},
    {'x': 'ASI', 'y': 'Fundamental data'},
    {'x': 'KOR', 'y': 'Fundamental data'},
    {'x': 'TWN', 'y': 'Fundamental data'},
    {'x': 'HKG', 'y': 'Fundamental data'},
    {'x': 'JPN', 'y': 'Fundamental data'},
    {'x': 'GLB', 'y': 'Analyst data'},
    {'x': 'ASI', 'y': 'Analyst data'},
    {'x': 'KOR', 'y': 'Analyst data'},
    {'x': 'TWN', 'y': 'Analyst data'},
    {'x': 'HKG', 'y': 'Analyst data'},
    {'x': 'JPN', 'y': 'Analyst data'},
    {'x': 'JPN', 'y': 'Broker'},
    {'x': 'GLB', 'y': 'News data'},
    {'x': 'ASI', 'y': 'News data'},
    {'x': 'KOR', 'y': 'News data'},
    {'x': 'TWN', 'y': 'News data'},
    {'x': 'HKG', 'y': 'News data'},
    {'x': 'JPN', 'y': 'News data'},
    {'x': 'GLB', 'y': 'Social media data'},
    {'x': 'ASI', 'y': 'Social media data'},
    {'x': 'HKG', 'y': 'Social media data'},
    {'x': 'JPN', 'y': 'Social media data'},
    {'x': 'JPN', 'y': 'Sentiment data'},
    {'x': 'GLB', 'y': 'Price volume data'},
    {'x': 'ASI', 'y': 'Price volume data'},
    {'x': 'KOR', 'y': 'Price volume data'},
    {'x': 'TWN', 'y': 'Price volume data'},
    {'x': 'HKG', 'y': 'Price volume data'},
    {'x': 'JPN', 'y': 'Price volume data'},
    {'x': 'GLB', 'y': 'Option data'},
    {'x': 'JPN', 'y': 'Option data'},
    {'x': 'GLB', 'y': 'Earnings'},
    {'x': 'ASI', 'y': 'Earnings'},
    {'x': 'KOR', 'y': 'Earnings'},
    {'x': 'TWN', 'y': 'Earnings'},
    {'x': 'HKG', 'y': 'Earnings'},
    {'x': 'JPN', 'y': 'Earnings'},
    {'x': 'ASI', 'y': 'Insiders'},
    {'x': 'KOR', 'y': 'Insiders'},
    {'x': 'HKG', 'y': 'Insiders'},
    {'x': 'JPN', 'y': 'Insiders'},
    {'x': 'JPN', 'y': 'Instiutional Ownership Data'},
    {'x': 'GLB', 'y': 'Short interest data'},
    {'x': 'ASI', 'y': 'Short interest data'},
    {'x': 'KOR', 'y': 'Short interest data'},
    {'x': 'TWN', 'y': 'Short interest data'},
    {'x': 'HKG', 'y': 'Short interest data'},
    {'x': 'JPN', 'y': 'Short interest data'},
    {'x': 'GLB', 'y': 'Macro data'},
    {'x': 'JPN', 'y': 'Macro data'},
    {'x': 'GLB', 'y': 'Other'},
    {'x': 'ASI', 'y': 'Other'},
    {'x': 'KOR', 'y': 'Other'},
    {'x': 'TWN', 'y': 'Other'},
    {'x': 'HKG', 'y': 'Other'},
    {'x': 'JPN', 'y': 'Other'},
    {'x': 'GLB', 'y': 'Risk data'},
    {'x': 'ASI', 'y': 'Risk data'},
    {'x': 'KOR', 'y': 'Risk data'},
    {'x': 'TWN', 'y': 'Risk data'},
    {'x': 'HKG', 'y': 'Risk data'},
    {'x': 'JPN', 'y': 'Risk data'},
    {'x': 'GLB', 'y': 'Model data'},
    {'x': 'ASI', 'y': 'Model data'},
    {'x': 'KOR', 'y': 'Model data'},
    {'x': 'TWN', 'y': 'Model data'},
    {'x': 'HKG', 'y': 'Model data'},
    {'x': 'JPN', 'y': 'Model data'}
]
